### ISSUE TITLE
SQL schema missing

### ISSUE THREAD

**Issue by markc** [thatsamguy/albatross#3]
Do you happen to have a *.sql file to set up the database?

It's too much effort to have to reverse engineer all the tables and the project looks quite interesting.

**Comment by thatsamguy** [comment]
Hi @markc - thanks for the interest. I've added the schema dump from my production install to try out.

Although I've not worked on this a while, feel free to ask any questions and I'll do my best answer and/or clean them up.

What OS were you targeting to test with?

**Comment by markc** [comment]
Great, thanks, I'll set it up and try again. I'm testing with Ubuntu 15.10 and the ondrej/php-7.0 packages, in LXD unpriv containers until I get something that works.

**Comment by markc** [comment]
Ah, thank you, that is much better, now I've got something that works! FWIW what I would like to do is spend the next couple of days making minor generic tweaks and maybe send you some pull requests. Then if I last through the 48 hour barrier I'll probably "go wild" and start making a php7 only version and start expanding my own service needs and ideas which will not suit your master branch. Ubuntu wily and php7 will be out by November so I hope to have something ready to **start** using for clients by then. I use a nginx+php-fpm, courier-mta/imap and powerdns combination.

Are you interested in a Bootstrap or Material Design frontend?

**Comment by thatsamguy** [comment]
That all sounds great. I don't mind which direction you look to take it in. If I see a PR that could be more generic I'll say so, otherwise feel to tinker and I'll likely merge most changes.

I've no preference on the frontend - whatever works best :)

**Comment by markc** [comment]
Frontend: good, so you don't care either way. Being mobile friendly is almost number one priority (for me) after getting to the point of understanding how the system is meant to work.

What about code style... would this be a bother for you?...

https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-2-coding-style-guide.md

Aside from style (and remove all tabs) the first pull requests would be to remove all **global $_SERVER** etc in functions because they are already super globals anyway.

I hope it's okay to ask some more questions in this ticket thread... what is the minimum version of PHP you need? ie; php 5.4 reaches end of life in a few days so if 5.5 is a suitable minimum then, amongst other things, short array [] syntax would be nice to use. Are you okay with short array syntax?

The main thing I am currently confused about is how to add new users and/or what signifies an admin user, or are there no user roles available at all?

**Comment by thatsamguy** [comment]
We can continue this discussion in #5 instead for future clarity.
